import type {
	LemmaKind,
	LemmaSubKind,
	SupportedLanguage,
	SurfaceKind,
} from "../../../types/public-types";

type TokenMap<T extends string> = Record<T, string>;
type InverseTokenMap<T extends string> = Record<string, T>;

function invert<T extends string>(
	name: string,
	tokens: TokenMap<T>,
): InverseTokenMap<T> {
	const inverse: Partial<Record<string, T>> = {};

	for (const [value, token] of Object.entries(tokens) as [T, string][]) {
		if (inverse[token] !== undefined) {
			throw new Error(`${name} token collision for ${token}`);
		}
		inverse[token] = value;
	}

	return inverse as InverseTokenMap<T>;
}

function valuesAsTokens<const T extends readonly string[]>(
	values: T,
): TokenMap<T[number]> {
	return Object.fromEntries(
		values.map((value) => [value, value]),
	) as TokenMap<T[number]>;
}

export const languageTokens = {
	de: "de",
	en: "en",
	he: "he",
} as const satisfies TokenMap<SupportedLanguage>;

export const entityKindTokens = {
	Lemma: "l",
	Surface: "s",
} as const;

export const surfaceKindTokens = {
	Citation: "c",
	Inflection: "i",
} as const satisfies TokenMap<SurfaceKind>;

export const lemmaKindTokens = {
	Lexeme: "l",
	Morpheme: "m",
	Phraseme: "p",
} as const satisfies TokenMap<LemmaKind>;

export const lemmaSubKindTokens = {
	ADJ: "j",
	ADP: "ap",
	ADV: "a",
	AUX: "au",
	Aphorism: "aph",
	CCONJ: "cc",
	Circumfix: "cf",
	Clitic: "cl",
	DET: "dt",
	DiscourseFormula: "df",
	Duplifix: "dfx",
	INTJ: "ij",
	Idiom: "id",
	Infix: "if",
	Interfix: "ix",
	NOUN: "n",
	NUM: "num",
	PART: "pt",
	PROPN: "pn",
	PRON: "pr",
	PUNCT: "pu",
	Prefix: "px",
	Proverb: "pv",
	Root: "r",
	SCONJ: "sc",
	SYM: "sy",
	Suffix: "sx",
	Suffixoid: "so",
	ToneMarking: "tm",
	Transfix: "tx",
	VERB: "v",
	X: "x",
} as const satisfies TokenMap<LemmaSubKind>;

export const featureNameTokens = {
	abbr: "ab",
	adpType: "adt",
	animacy: "an",
	aspect: "as",
	case: "ca",
	clusivity: "clu",
	conjType: "ct",
	definite: "def",
	degree: "deg",
	deixis: "dei",
	deixisRef: "dr",
	discourseFormulaRole: "dfr",
	evident: "ev",
	extPos: "ep",
	foreign: "fo",
	gender: "g",
	"gender[psor]": "gps",
	governedCase: "gc",
	hasGovPrep: "hgp",
	hasSepPrefix: "hsp",
	hebBinyan: "hb",
	hebExistential: "he",
	hyph: "hy",
	lexicallyReflexive: "lr",
	mood: "mo",
	nounClass: "nc",
	numForm: "nf",
	number: "nu",
	"number[psor]": "nps",
	numType: "nt",
	partType: "pat",
	person: "pe",
	phrasal: "phr",
	polarity: "pol",
	polite: "pli",
	poss: "pos",
	prefix: "pre",
	pronType: "prt",
	punctType: "put",
	reflex: "re",
	style: "st",
	tense: "te",
	variant: "va",
	verbForm: "vf",
	verbType: "vt",
	voice: "vo",
} as const;

export const featureValueTokens = {
	abbr: valuesAsTokens(["Yes"]),
	adpType: valuesAsTokens(["Circ", "Post", "Prep", "Voc"]),
	animacy: valuesAsTokens(["Anim", "Hum", "Inan", "Nhum"]),
	aspect: valuesAsTokens(["Hab", "Imp", "Iter", "Perf", "Prog", "Prosp"]),
	case: valuesAsTokens([
		"Acc",
		"Abe",
		"Ben",
		"Cau",
		"Cmp",
		"Cns",
		"Com",
		"Dat",
		"Dis",
		"Equ",
		"Gen",
		"Ins",
		"Par",
		"Tem",
		"Abl",
		"Add",
		"Ade",
		"All",
		"Del",
		"Ela",
		"Ess",
		"Ill",
		"Ine",
		"Lat",
		"Loc",
		"Nom",
		"Per",
		"Sbe",
		"Sbl",
		"Spl",
		"Sub",
		"Sup",
		"Ter",
	]),
	clusivity: valuesAsTokens(["Ex", "In"]),
	conjType: valuesAsTokens(["Comp", "Oper"]),
	definite: valuesAsTokens(["Com", "Cons", "Def", "Ind", "Spec"]),
	degree: valuesAsTokens(["Abs", "Aug", "Cmp", "Dim", "Equ", "Pos", "Sup"]),
	deixis: valuesAsTokens([
		"Abv",
		"Bel",
		"Even",
		"Med",
		"Nvis",
		"Prox",
		"Remt",
	]),
	deixisRef: valuesAsTokens(["1", "2"]),
	discourseFormulaRole: valuesAsTokens([
		"Greeting",
		"Farewell",
		"Apology",
		"Thanks",
		"Acknowledgment",
		"Refusal",
		"Request",
		"Reaction",
		"Initiation",
		"Transition",
	]),
	evident: valuesAsTokens(["Fh", "Nfh"]),
	extPos: valuesAsTokens([
		"ADJ",
		"ADP",
		"ADV",
		"AUX",
		"CCONJ",
		"DET",
		"INTJ",
		"PRON",
		"PROPN",
		"SCONJ",
	]),
	foreign: valuesAsTokens(["Yes"]),
	gender: valuesAsTokens(["Com", "Fem", "Masc", "Neut"]),
	"gender[psor]": valuesAsTokens(["Com", "Fem", "Masc", "Neut"]),
	governedCase: valuesAsTokens([
		"Acc",
		"Abe",
		"Ben",
		"Cau",
		"Cmp",
		"Cns",
		"Com",
		"Dat",
		"Dis",
		"Equ",
		"Gen",
		"Ins",
		"Par",
		"Tem",
		"Abl",
		"Add",
		"Ade",
		"All",
		"Del",
		"Ela",
		"Ess",
		"Ill",
		"Ine",
		"Lat",
		"Loc",
		"Nom",
		"Per",
		"Sbe",
		"Sbl",
		"Spl",
		"Sub",
		"Sup",
		"Ter",
	]),
	hasGovPrep: {},
	hasSepPrefix: {},
	hebBinyan: valuesAsTokens([
		"HIFIL",
		"HITPAEL",
		"HUFAL",
		"NIFAL",
		"PAAL",
		"PIEL",
		"PUAL",
	]),
	hebExistential: valuesAsTokens(["Yes"]),
	hyph: valuesAsTokens(["Yes"]),
	lexicallyReflexive: valuesAsTokens(["Yes"]),
	mood: valuesAsTokens([
		"Adm",
		"Cnd",
		"Des",
		"Imp",
		"Ind",
		"Int",
		"Irr",
		"Jus",
		"Nec",
		"Opt",
		"Pot",
		"Prp",
		"Qot",
		"Sub",
	]),
	nounClass: valuesAsTokens([
		"Bantu1",
		"Bantu2",
		"Bantu3",
		"Bantu4",
		"Bantu5",
		"Bantu6",
		"Bantu7",
		"Bantu8",
		"Bantu9",
		"Bantu10",
		"Bantu11",
		"Bantu12",
		"Bantu13",
		"Bantu14",
		"Bantu15",
		"Bantu16",
		"Bantu17",
		"Bantu18",
		"Bantu19",
		"Bantu20",
		"Bantu21",
		"Bantu22",
		"Bantu23",
		"Wol1",
		"Wol2",
		"Wol3",
		"Wol4",
		"Wol5",
		"Wol6",
		"Wol7",
		"Wol8",
		"Wol9",
		"Wol10",
		"Wol11",
		"Wol12",
	]),
	numForm: valuesAsTokens(["Combi", "Digit", "Roman", "Word"]),
	number: valuesAsTokens([
		"Coll",
		"Count",
		"Dual",
		"Grpa",
		"Grpl",
		"Inv",
		"Pauc",
		"Plur",
		"Ptan",
		"Sing",
		"Tri",
	]),
	"number[psor]": valuesAsTokens([
		"Coll",
		"Count",
		"Dual",
		"Grpa",
		"Grpl",
		"Inv",
		"Pauc",
		"Plur",
		"Ptan",
		"Sing",
		"Tri",
	]),
	numType: valuesAsTokens([
		"Card",
		"Dist",
		"Frac",
		"Mult",
		"Ord",
		"Range",
		"Sets",
	]),
	partType: valuesAsTokens(["Inf", "Mod", "Res", "Vbp"]),
	person: valuesAsTokens(["0", "1", "2", "3", "4"]),
	phrasal: valuesAsTokens(["Yes"]),
	polarity: valuesAsTokens(["Neg", "Pos"]),
	polite: valuesAsTokens(["Elev", "Form", "Humb", "Infm"]),
	poss: valuesAsTokens(["Yes"]),
	prefix: valuesAsTokens(["Yes"]),
	pronType: valuesAsTokens([
		"Art",
		"Dem",
		"Emp",
		"Exc",
		"Ind",
		"Int",
		"Neg",
		"Prs",
		"Rcp",
		"Rel",
		"Tot",
	]),
	punctType: valuesAsTokens([
		"Brck",
		"Colo",
		"Comm",
		"Dash",
		"Elip",
		"Excl",
		"Peri",
		"Qest",
		"Quot",
	]),
	reflex: valuesAsTokens(["Yes"]),
	style: valuesAsTokens([
		"Arch",
		"Coll",
		"Expr",
		"Form",
		"Rare",
		"Slng",
		"Vrnc",
		"Vulg",
	]),
	tense: valuesAsTokens(["Fut", "Imp", "Past", "Pqp", "Pres"]),
	variant: valuesAsTokens(["Short"]),
	verbForm: valuesAsTokens([
		"Conv",
		"Fin",
		"Gdv",
		"Ger",
		"Inf",
		"Part",
		"Sup",
		"Vnoun",
	]),
	verbType: valuesAsTokens(["Aux", "Cop", "Light", "Mod", "Quasi"]),
	voice: valuesAsTokens([
		"Act",
		"Antip",
		"Bfoc",
		"Cau",
		"Dir",
		"Inv",
		"Lfoc",
		"Mid",
		"Pass",
		"Rcp",
	]),
} as const satisfies {
	[K in keyof typeof featureNameTokens]: TokenMap<string>;
};

export type FeatureNameTokenKey = keyof typeof featureNameTokens;

export const inverseLanguageTokens = invert("language", languageTokens);
export const inverseEntityKindTokens = invert("entityKind", entityKindTokens);
export const inverseSurfaceKindTokens = invert(
	"surfaceKind",
	surfaceKindTokens,
);
export const inverseLemmaKindTokens = invert("lemmaKind", lemmaKindTokens);
export const inverseLemmaSubKindTokens = invert(
	"lemmaSubKind",
	lemmaSubKindTokens,
);
export const inverseFeatureNameTokens = invert(
	"featureName",
	featureNameTokens,
);
export const inverseFeatureValueTokens = Object.fromEntries(
	Object.entries(featureValueTokens).map(([name, tokens]) => [
		name,
		invert(`${name} feature value`, tokens as TokenMap<string>),
	]),
) as unknown as {
	[K in keyof typeof featureValueTokens]: InverseTokenMap<
		keyof (typeof featureValueTokens)[K] & string
	>;
};

export const rawStringFeatureNames = new Set<FeatureNameTokenKey>([
	"hasGovPrep",
	"hasSepPrefix",
]);
