export const goodBoys = [
	"[Am] nächsten Morgen war alles anders.",
	"Am [nächsten] Morgen war alles anders.",
	"Am nächsten Morgen war alles [anders].",
	"Auf der Karte sind drei [Seen] eingezeichnet.",
	"Auf der Karte sind drei Seen [eingezeichnet].",
	"Bitte folgen Sie [Ihrem] Ansprechpartner.",
	"Das ist [nicht] mein Problem.",
	"Das ist schwer [zu] erklären.",
	"Das [muss] heute noch raus.",
	"Das muss heute noch [raus].",
	"Das rote [Band] lag auf dem Geschenk.",
	"Das rote Band [lag] auf dem Geschenk.",
	"Das rote Band lag [auf] dem Geschenk.",
	"Das [Schloss] an der Tür klemmt.",
	"Das [Schloss] über dem Fluss wurde renoviert.",
	"Das [Un]- in Unkosten wirkt historisch irritierend.",
	"Das wäre [fast] schief gewesen.",
	"Der Autor, [dessen] Buch fehlt, wartet draußen.",
	"Der dritte [Band] ist längst vergriffen.",
	"Der Fährmann hat uns [übergesetzt].",
	"Der [Kiefer] schmerzte nach der Operation.",
	"Der Laster [fuhr] das Schild um.",
	"Der [Leiter] der Werkstatt kam später.",
	"Die alte [Kiefer] steht am Hang.",
	"Die [Band] spielt heute im Kellerclub.",
	"Die [Leiter] wackelte auf dem nassen Boden.",
	"Die [linke] Hand zitterte.",
	"Die [Mutter] passt nicht auf diese Schraube.",
	"Die Zeugin, [deren] Aussage zählt, bleibt anonym.",
	`[Einst] ging er an Ufers Rand
mit der Mappe in der Hand.`,
	`Einst [ging] er an Ufers Rand
mit der Mappe in der Hand.`,
	`Einst ging er [an] Ufers Rand
mit der Mappe in der Hand.`,
	`Einst ging er an [Ufers] Rand
mit der Mappe in der Hand.`,
	"Er ging [zum] Bahnhof.",
	"Er [muss] heute arbeiten.",
	"Er [wartet] auf den Nachtbus.",
	`Er [wog] vielleicht ein halbes Lot –
und war am fünften Tage tot.
`,
	`Er wog vielleicht ein halbes Lot –
und war am fünften Tage [tot].
`,
	"[Geh] bitte nicht ohne Jacke raus.",
	"Ich suche einen [besseren] Ansatz.",
	"Im Heft stand [Filosofie] statt Philosophie.",
	"In [ge]lacht markieren ge- und -t zusammen das Partizip.",
	"Meine [Mutter] ruft jeden Sonntag an.",
	"Mit den [Kindern] ist es nie langweilig.",
	"Mit [keinem] Wort erwähnte sie den Plan.",
	"Nach [manchem] Fehler lernt man schneller.",
	"[Pass] auf dich auf!",
	"Pass [auf] dich auf!",
	"Pass auf [dich] auf!",
	"Pass auf dich [auf]!",
	"Sie [erinnert] sich an den Geruch.",
	"Sie folgte ihrem [Herzen].",
	"Sie sprang [ins] kalte Wasser.",
	"Sie [übersetzt] den Vertrag ins Deutsche.",
	"Sie [umfuhr] die Baustelle weiträumig.",
	"Sie wurde um Geduld [gebeten].",
	`[Sieh] einmal, hier steht er, 
pfui, der Struwwelpeter!`,
	`Sieh einmal, [hier] steht er, 
pfui, der Struwwelpeter!`,
	`Sieh einmal, hier [steht] er, 
pfui, der Struwwelpeter!`,
	`Sieh einmal, hier steht [er], 
pfui, der Struwwelpeter!`,
	`Sieh einmal, hier steht er, 
[pfui], der Struwwelpeter!`,
	`Sieh einmal, hier steht er, 
pfui, [der] Struwwelpeter!`,
	`Sieh einmal, hier steht er, 
pfui, der [Struwwelpeter]!`,
	`Und Minz und Maunz, [die] schreien
gar jämmerlich zu zweien`,
	`Und Minz und Maunz, die schreien
gar jämmerlich [zu] zweien`,
	`Und Minz und Maunz, die schreien
gar jämmerlich zu [zweien]`,
	"Unter falschem [Namen] mietete er das Zimmer.",
	"Viele [deutschsprachigen] Quellen fehlen noch.",
	"Wir [hätten] gern mehr Zeit.",
	"Wir liefen den Fluss [entlang].",
] as const;

export const goodBoySet = new Set<string>(goodBoys);
